services:
  backend:
    build: ./Backend
    container_name: naksh-backend
    ports:
      - "5000:5000"
    env_file:
      - ./Backend/.env

  frontend:
    build: ./Frontend
    container_name: naksh-frontend
    ports:
      - "5173:5173"
    command: npm run dev
    depends_on:
      - backend
